// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: idl/proto/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Numeric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Numeric:
	//	*Numeric_UINT32
	//	*Numeric_INT32
	//	*Numeric_UINT64
	//	*Numeric_INT64
	//	*Numeric_FLOAT32
	//	*Numeric_FLOAT64
	Numeric isNumeric_Numeric `protobuf_oneof:"Numeric"`
}

func (x *Numeric) Reset() {
	*x = Numeric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_proto_v1_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Numeric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Numeric) ProtoMessage() {}

func (x *Numeric) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_v1_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Numeric.ProtoReflect.Descriptor instead.
func (*Numeric) Descriptor() ([]byte, []int) {
	return file_idl_proto_v1_common_proto_rawDescGZIP(), []int{0}
}

func (m *Numeric) GetNumeric() isNumeric_Numeric {
	if m != nil {
		return m.Numeric
	}
	return nil
}

func (x *Numeric) GetUINT32() uint32 {
	if x, ok := x.GetNumeric().(*Numeric_UINT32); ok {
		return x.UINT32
	}
	return 0
}

func (x *Numeric) GetINT32() int32 {
	if x, ok := x.GetNumeric().(*Numeric_INT32); ok {
		return x.INT32
	}
	return 0
}

func (x *Numeric) GetUINT64() uint64 {
	if x, ok := x.GetNumeric().(*Numeric_UINT64); ok {
		return x.UINT64
	}
	return 0
}

func (x *Numeric) GetINT64() int64 {
	if x, ok := x.GetNumeric().(*Numeric_INT64); ok {
		return x.INT64
	}
	return 0
}

func (x *Numeric) GetFLOAT32() float32 {
	if x, ok := x.GetNumeric().(*Numeric_FLOAT32); ok {
		return x.FLOAT32
	}
	return 0
}

func (x *Numeric) GetFLOAT64() float64 {
	if x, ok := x.GetNumeric().(*Numeric_FLOAT64); ok {
		return x.FLOAT64
	}
	return 0
}

type isNumeric_Numeric interface {
	isNumeric_Numeric()
}

type Numeric_UINT32 struct {
	UINT32 uint32 `protobuf:"varint,1,opt,name=UINT32,proto3,oneof"`
}

type Numeric_INT32 struct {
	INT32 int32 `protobuf:"varint,2,opt,name=INT32,proto3,oneof"`
}

type Numeric_UINT64 struct {
	UINT64 uint64 `protobuf:"varint,3,opt,name=UINT64,proto3,oneof"`
}

type Numeric_INT64 struct {
	INT64 int64 `protobuf:"varint,4,opt,name=INT64,proto3,oneof"`
}

type Numeric_FLOAT32 struct {
	FLOAT32 float32 `protobuf:"fixed32,5,opt,name=FLOAT32,proto3,oneof"`
}

type Numeric_FLOAT64 struct {
	FLOAT64 float64 `protobuf:"fixed64,6,opt,name=FLOAT64,proto3,oneof"`
}

func (*Numeric_UINT32) isNumeric_Numeric() {}

func (*Numeric_INT32) isNumeric_Numeric() {}

func (*Numeric_UINT64) isNumeric_Numeric() {}

func (*Numeric_INT64) isNumeric_Numeric() {}

func (*Numeric_FLOAT32) isNumeric_Numeric() {}

func (*Numeric_FLOAT64) isNumeric_Numeric() {}

type String struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to String_:
	//	*String_STRING
	//	*String_BYTES
	String_ isString_String_ `protobuf_oneof:"String"`
}

func (x *String) Reset() {
	*x = String{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_proto_v1_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_v1_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_idl_proto_v1_common_proto_rawDescGZIP(), []int{1}
}

func (m *String) GetString_() isString_String_ {
	if m != nil {
		return m.String_
	}
	return nil
}

func (x *String) GetSTRING() string {
	if x, ok := x.GetString_().(*String_STRING); ok {
		return x.STRING
	}
	return ""
}

func (x *String) GetBYTES() []byte {
	if x, ok := x.GetString_().(*String_BYTES); ok {
		return x.BYTES
	}
	return nil
}

type isString_String_ interface {
	isString_String_()
}

type String_STRING struct {
	STRING string `protobuf:"bytes,1,opt,name=STRING,proto3,oneof"`
}

type String_BYTES struct {
	BYTES []byte `protobuf:"bytes,2,opt,name=BYTES,proto3,oneof"`
}

func (*String_STRING) isString_String_() {}

func (*String_BYTES) isString_String_() {}

type SpanVendor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to SpanVendor:
	//	*SpanVendor_DataDog
	//	*SpanVendor_Jaeger
	//	*SpanVendor_OpenTelemetry
	//	*SpanVendor_Pinpoint
	//	*SpanVendor_SkyWalking
	//	*SpanVendor_Zipkin
	//	*SpanVendor_OpenTracingeBPF
	//	*SpanVendor_OpenTracingGo
	SpanVendor isSpanVendor_SpanVendor `protobuf_oneof:"SpanVendor"`
}

func (x *SpanVendor) Reset() {
	*x = SpanVendor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_proto_v1_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpanVendor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanVendor) ProtoMessage() {}

func (x *SpanVendor) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_v1_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanVendor.ProtoReflect.Descriptor instead.
func (*SpanVendor) Descriptor() ([]byte, []int) {
	return file_idl_proto_v1_common_proto_rawDescGZIP(), []int{2}
}

func (m *SpanVendor) GetSpanVendor() isSpanVendor_SpanVendor {
	if m != nil {
		return m.SpanVendor
	}
	return nil
}

func (x *SpanVendor) GetDataDog() string {
	if x, ok := x.GetSpanVendor().(*SpanVendor_DataDog); ok {
		return x.DataDog
	}
	return ""
}

func (x *SpanVendor) GetJaeger() string {
	if x, ok := x.GetSpanVendor().(*SpanVendor_Jaeger); ok {
		return x.Jaeger
	}
	return ""
}

func (x *SpanVendor) GetOpenTelemetry() string {
	if x, ok := x.GetSpanVendor().(*SpanVendor_OpenTelemetry); ok {
		return x.OpenTelemetry
	}
	return ""
}

func (x *SpanVendor) GetPinpoint() string {
	if x, ok := x.GetSpanVendor().(*SpanVendor_Pinpoint); ok {
		return x.Pinpoint
	}
	return ""
}

func (x *SpanVendor) GetSkyWalking() string {
	if x, ok := x.GetSpanVendor().(*SpanVendor_SkyWalking); ok {
		return x.SkyWalking
	}
	return ""
}

func (x *SpanVendor) GetZipkin() string {
	if x, ok := x.GetSpanVendor().(*SpanVendor_Zipkin); ok {
		return x.Zipkin
	}
	return ""
}

func (x *SpanVendor) GetOpenTracingeBPF() string {
	if x, ok := x.GetSpanVendor().(*SpanVendor_OpenTracingeBPF); ok {
		return x.OpenTracingeBPF
	}
	return ""
}

func (x *SpanVendor) GetOpenTracingGo() string {
	if x, ok := x.GetSpanVendor().(*SpanVendor_OpenTracingGo); ok {
		return x.OpenTracingGo
	}
	return ""
}

type isSpanVendor_SpanVendor interface {
	isSpanVendor_SpanVendor()
}

type SpanVendor_DataDog struct {
	DataDog string `protobuf:"bytes,1,opt,name=DataDog,proto3,oneof"`
}

type SpanVendor_Jaeger struct {
	Jaeger string `protobuf:"bytes,2,opt,name=Jaeger,proto3,oneof"`
}

type SpanVendor_OpenTelemetry struct {
	OpenTelemetry string `protobuf:"bytes,3,opt,name=OpenTelemetry,proto3,oneof"`
}

type SpanVendor_Pinpoint struct {
	Pinpoint string `protobuf:"bytes,4,opt,name=Pinpoint,proto3,oneof"`
}

type SpanVendor_SkyWalking struct {
	SkyWalking string `protobuf:"bytes,5,opt,name=SkyWalking,proto3,oneof"`
}

type SpanVendor_Zipkin struct {
	Zipkin string `protobuf:"bytes,6,opt,name=Zipkin,proto3,oneof"`
}

type SpanVendor_OpenTracingeBPF struct {
	OpenTracingeBPF string `protobuf:"bytes,7,opt,name=OpenTracingeBPF,proto3,oneof"`
}

type SpanVendor_OpenTracingGo struct {
	OpenTracingGo string `protobuf:"bytes,8,opt,name=OpenTracingGo,proto3,oneof"`
}

func (*SpanVendor_DataDog) isSpanVendor_SpanVendor() {}

func (*SpanVendor_Jaeger) isSpanVendor_SpanVendor() {}

func (*SpanVendor_OpenTelemetry) isSpanVendor_SpanVendor() {}

func (*SpanVendor_Pinpoint) isSpanVendor_SpanVendor() {}

func (*SpanVendor_SkyWalking) isSpanVendor_SpanVendor() {}

func (*SpanVendor_Zipkin) isSpanVendor_SpanVendor() {}

func (*SpanVendor_OpenTracingeBPF) isSpanVendor_SpanVendor() {}

func (*SpanVendor_OpenTracingGo) isSpanVendor_SpanVendor() {}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	Coding  string `protobuf:"bytes,4,opt,name=Coding,proto3" json:"Coding,omitempty"`
	Payload []byte `protobuf:"bytes,5,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_proto_v1_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_v1_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_idl_proto_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetCoding() string {
	if x != nil {
		return x.Coding
	}
	return ""
}

func (x *Response) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_idl_proto_v1_common_proto protoreflect.FileDescriptor

var file_idl_proto_v1_common_proto_rawDesc = []byte{
	0x0a, 0x19, 0x69, 0x64, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f, 0x70, 0x65,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x22, 0xb0, 0x01, 0x0a, 0x07,
	0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x06, 0x55, 0x49, 0x4e, 0x54, 0x33,
	0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x06, 0x55, 0x49, 0x4e, 0x54, 0x33,
	0x32, 0x12, 0x16, 0x0a, 0x05, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x05, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x12, 0x18, 0x0a, 0x06, 0x55, 0x49, 0x4e,
	0x54, 0x36, 0x34, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x06, 0x55, 0x49, 0x4e,
	0x54, 0x36, 0x34, 0x12, 0x16, 0x0a, 0x05, 0x49, 0x4e, 0x54, 0x36, 0x34, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x00, 0x52, 0x05, 0x49, 0x4e, 0x54, 0x36, 0x34, 0x12, 0x1a, 0x0a, 0x07, 0x46,
	0x4c, 0x4f, 0x41, 0x54, 0x33, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x07,
	0x46, 0x4c, 0x4f, 0x41, 0x54, 0x33, 0x32, 0x12, 0x1a, 0x0a, 0x07, 0x46, 0x4c, 0x4f, 0x41, 0x54,
	0x36, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x07, 0x46, 0x4c, 0x4f, 0x41,
	0x54, 0x36, 0x34, 0x42, 0x09, 0x0a, 0x07, 0x4e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x22, 0x44,
	0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49,
	0x4e, 0x47, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x53, 0x54, 0x52, 0x49,
	0x4e, 0x47, 0x12, 0x16, 0x0a, 0x05, 0x42, 0x59, 0x54, 0x45, 0x53, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x05, 0x42, 0x59, 0x54, 0x45, 0x53, 0x42, 0x08, 0x0a, 0x06, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x22, 0xa6, 0x02, 0x0a, 0x0a, 0x53, 0x70, 0x61, 0x6e, 0x56, 0x65, 0x6e,
	0x64, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x07, 0x44, 0x61, 0x74, 0x61, 0x44, 0x6f, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x44, 0x61, 0x74, 0x61, 0x44, 0x6f, 0x67, 0x12,
	0x18, 0x0a, 0x06, 0x4a, 0x61, 0x65, 0x67, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x06, 0x4a, 0x61, 0x65, 0x67, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0d, 0x4f, 0x70, 0x65,
	0x6e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0d, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x12, 0x1c, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x50, 0x69, 0x6e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x20, 0x0a, 0x0a, 0x53, 0x6b, 0x79, 0x57, 0x61, 0x6c, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x53, 0x6b, 0x79, 0x57, 0x61, 0x6c, 0x6b, 0x69, 0x6e,
	0x67, 0x12, 0x18, 0x0a, 0x06, 0x5a, 0x69, 0x70, 0x6b, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x06, 0x5a, 0x69, 0x70, 0x6b, 0x69, 0x6e, 0x12, 0x2a, 0x0a, 0x0f, 0x4f,
	0x70, 0x65, 0x6e, 0x54, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x65, 0x42, 0x50, 0x46, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0f, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x72, 0x61, 0x63,
	0x69, 0x6e, 0x67, 0x65, 0x42, 0x50, 0x46, 0x12, 0x26, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x6e, 0x54,
	0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0d, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x42,
	0x0c, 0x0a, 0x0a, 0x53, 0x70, 0x61, 0x6e, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x22, 0x88, 0x01,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x64, 0x69, 0x6e, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x18,
	0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x6f, 0x64, 0x61, 0x70, 0x65, 0x57, 0x69, 0x6c,
	0x64, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x2d, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_proto_v1_common_proto_rawDescOnce sync.Once
	file_idl_proto_v1_common_proto_rawDescData = file_idl_proto_v1_common_proto_rawDesc
)

func file_idl_proto_v1_common_proto_rawDescGZIP() []byte {
	file_idl_proto_v1_common_proto_rawDescOnce.Do(func() {
		file_idl_proto_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_proto_v1_common_proto_rawDescData)
	})
	return file_idl_proto_v1_common_proto_rawDescData
}

var file_idl_proto_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_idl_proto_v1_common_proto_goTypes = []interface{}{
	(*Numeric)(nil),    // 0: opentracing.v1.Numeric
	(*String)(nil),     // 1: opentracing.v1.String
	(*SpanVendor)(nil), // 2: opentracing.v1.SpanVendor
	(*Response)(nil),   // 3: opentracing.v1.Response
}
var file_idl_proto_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_proto_v1_common_proto_init() }
func file_idl_proto_v1_common_proto_init() {
	if File_idl_proto_v1_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_proto_v1_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Numeric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_proto_v1_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*String); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_proto_v1_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpanVendor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_proto_v1_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_idl_proto_v1_common_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Numeric_UINT32)(nil),
		(*Numeric_INT32)(nil),
		(*Numeric_UINT64)(nil),
		(*Numeric_INT64)(nil),
		(*Numeric_FLOAT32)(nil),
		(*Numeric_FLOAT64)(nil),
	}
	file_idl_proto_v1_common_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*String_STRING)(nil),
		(*String_BYTES)(nil),
	}
	file_idl_proto_v1_common_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*SpanVendor_DataDog)(nil),
		(*SpanVendor_Jaeger)(nil),
		(*SpanVendor_OpenTelemetry)(nil),
		(*SpanVendor_Pinpoint)(nil),
		(*SpanVendor_SkyWalking)(nil),
		(*SpanVendor_Zipkin)(nil),
		(*SpanVendor_OpenTracingeBPF)(nil),
		(*SpanVendor_OpenTracingGo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_proto_v1_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idl_proto_v1_common_proto_goTypes,
		DependencyIndexes: file_idl_proto_v1_common_proto_depIdxs,
		MessageInfos:      file_idl_proto_v1_common_proto_msgTypes,
	}.Build()
	File_idl_proto_v1_common_proto = out.File
	file_idl_proto_v1_common_proto_rawDesc = nil
	file_idl_proto_v1_common_proto_goTypes = nil
	file_idl_proto_v1_common_proto_depIdxs = nil
}
